#' Identify edges given functions
#' 
#' @param func Functions, an object class generated by \code{function_from_edge}
#' or \code{function_from_user} functions.
#' 
#' @return A data frame which include the columns 'from' and 'to in this order.
#' 
#' @keywords edge, function
#' 
#' @export
#' 
#' @examples 
#' 
#' data(functions)
#' edge_from_function(functions)

edge_from_function=function(func){
  # Check if 'func' is 'Functions'
  if(class(func)!='Functions'){
    stop(
      paste0(
        '\n'
        ,'The argument \'func\' is not of class \'Functions\'. Please use\n'
        ,'function_from_edge() or function_from_user() to create valid input\n'
        ,'for this function.'
      )
    )
  }
  
  # List arguments in each function
  arg=
    func %>%
    lapply(formals) %>%
    lapply(names)
  
  # Filter arguments of functions from non-terminal vertices
  v_nonterm_arg=
    arg %>%
    .[sapply(.,\(x)length(x[x!='n'])>0)]
  
  # Create an edge from each argument to the non-terminal vertex
  e=v_nonterm_arg %>%
    lapply(X=names(.),Y=.,\(X,Y)data.frame(from=Y[[X]],to=X)) %>%
    do.call(rbind,.)
  
  # Return edges
  e
}